"""add habit tracking unit and log amount

Revision ID: 30f05060afb3
Revises: 8a0fd47abbe4
Create Date: 2026-08-18 03:16:39.550091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f05060afb3'
down_revision: Union[str, Sequence[str], None] = '8a0fd47abbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('habits', sa.Column('tracking_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'tracking_unit')
    op.drop_column('habit_logs', 'amount')
    # ### end Alembic commands ###
