"""add habit category and log note

Revision ID: 872c6d1ed084
Revises: 30f05060afb3
Create Date: 2026-08-18 03:48:39.339623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872c6d1ed084'
down_revision: Union[str, Sequence[str], None] = '30f05060afb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit_logs', sa.Column('note', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'category')
    op.drop_column('habit_logs', 'note')
    # ### end Alembic commands ###
